export type Rating = 0 | 1 | 2 | 3 | 4 | 5;
export interface Category { id:string; name:string; weight:number; questions:string[]; recommendation:string }
export const CATEGORIES:Category[]=[
{id:'technical',name:'Technical Capability',weight:20,questions:['Proven experience with the required technology stack','Delivered projects with similar complexity','Can explain the proposed architecture clearly','Follows coding standards and code-review practices','Can handle APIs, integrations, cloud infrastructure and scalability','Has qualified developers, architects and QA engineers'],recommendation:'Request a technical architecture review, code samples, team profiles and proof of similar implementations.'},
{id:'industry',name:'Relevant Industry Experience',weight:10,questions:['Worked in the client’s industry','Understands relevant business workflows','Can show relevant case studies','Understands industry-specific risks or regulations','References from similar projects can be verified'],recommendation:'Ask for relevant workflows, client references and evidence that the vendor understands your operational requirements.'},
{id:'discovery',name:'Project Discovery and Requirements',weight:10,questions:['Asks detailed business and technical questions','Has a structured discovery process','Documents scope, assumptions and exclusions','Clearly defines user roles, workflows and acceptance criteria','Identifies risks before development begins'],recommendation:'Require a documented discovery phase covering scope, assumptions, workflows, acceptance criteria and risks.'},
{id:'delivery',name:'Delivery Process and Project Management',weight:15,questions:['Clearly explains the development methodology','Documents milestones, sprints and deliverables','Provides regular demos and progress updates','Has a clear process for scope changes','Uses project-management tools transparently','Defines testing, deployment and approval stages'],recommendation:'Require documented milestones, sprint plans, reporting frequency, acceptance criteria and escalation procedures.'},
{id:'communication',name:'Communication and Collaboration',weight:10,questions:['Responsive during sales and discovery','Defines channels and meeting schedules','Provides a dedicated project manager or contact','Explains technical issues in business language','Time-zone and language differences are manageable','Defines escalation handling'],recommendation:'Define response-time expectations, meeting cadence, responsible contacts and escalation channels in writing.'},
{id:'qa',name:'Quality Assurance and Testing',weight:10,questions:['Has a documented QA process','Performs functional and regression testing','Includes security, performance and compatibility tests','Shares test cases and bug reports','Supports user acceptance testing','Clearly defines release criteria'],recommendation:'Request a complete test strategy covering functional, regression, performance, security and user-acceptance testing.'},
{id:'security',name:'Security, Privacy and Compliance',weight:10,questions:['Follows secure development practices','Manages access controls and permissions securely','Protects client data during development and testing','Provides NDAs and confidentiality terms','Understands applicable privacy and compliance requirements','Defines backups, incident response and security reporting'],recommendation:'Request secure-development policies, access-control procedures, backup plans, incident response and compliance evidence.'},
{id:'pricing',name:'Pricing and Commercial Transparency',weight:5,questions:['Proposal is itemised and understandable','Inclusions and exclusions are documented','Payment milestones link to deliverables','Third-party, hosting and maintenance costs are disclosed','Change-request pricing is clear','No hidden charges or unclear assumptions'],recommendation:'Require itemised pricing, exclusions, third-party costs, payment milestones and change-request rates.'},
{id:'ownership',name:'Ownership, Documentation and Exit Protection',weight:5,questions:['Client owns source code and deliverables after payment','Client controls repository, cloud and important accounts','Technical documentation is included','A clear handover process exists','Another team can continue the project','Vendor-lock-in risks are addressed'],recommendation:'Ensure the contract provides source-code ownership, repository access, documentation, credential transfer and transition support.'},
{id:'support',name:'Post-Launch Support and Long-Term Fit',weight:5,questions:['Warranty or bug-fix period is included','Support response times are defined','Maintenance and enhancement options are available','Team can support future growth and scaling','Monitoring, backup and incident procedures exist','Vendor demonstrates long-term business stability'],recommendation:'Define warranty duration, support response times, maintenance pricing and production incident handling.'}
];
export const RED_FLAGS=['Refuses to provide client references','Cannot show relevant work or case studies','Proposal contains unclear scope','Requests full payment before meaningful delivery','Will not provide repository access','Does not confirm source-code ownership','Uses client production credentials insecurely','Has no documented testing process','Has no backup or recovery plan','Has no written change-request process','Uses unusually low pricing without clear explanation','Makes unrealistic delivery promises','Avoids discussing maintenance and support','Cannot identify the actual development team','Outsources work without disclosure','Has poor or inconsistent communication','Will not sign an NDA or contract','Requires vendor-controlled hosting without transfer rights','Cannot explain data-security practices','Has unresolved legal, ownership or reputation concerns'];
export type Ratings=Record<string,Rating>;
export interface CategoryResult{ id:string;name:string;weight:number;assessed:number;total:number;average:number|null;percentage:number|null;weighted:number;lowQuestions:string[];recommendation:string }
export interface ScoreResult{finalScore:number;assessedQuestions:number;unansweredQuestions:number;assessedWeight:number;categories:CategoryResult[];rating:string;recommendation:string;incomplete:boolean}
export function calculateVendorScore(ratings:Ratings):ScoreResult{let weighted=0,assessedWeight=0,assessedQuestions=0,total=0;const categories=CATEGORIES.map(c=>{const values=c.questions.map((_,i)=>ratings[`${c.id}-${i}`]||0).filter(v=>v>0);total+=c.questions.length;assessedQuestions+=values.length;if(!values.length)return{id:c.id,name:c.name,weight:c.weight,assessed:0,total:c.questions.length,average:null,percentage:null,weighted:0,lowQuestions:[],recommendation:c.recommendation};const average=values.reduce<number>((a,b)=>a+b,0)/values.length,percentage=average/5*100,contribution=percentage*(c.weight/100);weighted+=contribution;assessedWeight+=c.weight;return{id:c.id,name:c.name,weight:c.weight,assessed:values.length,total:c.questions.length,average,percentage,weighted:contribution,lowQuestions:c.questions.filter((_,i)=>{const v=ratings[`${c.id}-${i}`]||0;return v>0&&v<3}),recommendation:c.recommendation}});const finalScore=assessedWeight?Math.min(100,Math.max(0,weighted/assessedWeight*100)):0;const band=getScoreBand(finalScore);return{finalScore,assessedQuestions,unansweredQuestions:total-assessedQuestions,assessedWeight,categories,rating:band.rating,recommendation:band.recommendation,incomplete:assessedQuestions<total};}
export function getScoreBand(s:number){if(s>=90)return{rating:'Excellent Strategic Partner',recommendation:'The vendor demonstrates strong capability, transparency and delivery maturity. Proceed to final reference checks, contract review and technical validation.'};if(s>=75)return{rating:'Strong Candidate',recommendation:'The vendor appears capable, but important commercial, technical and delivery terms should be confirmed before signing.'};if(s>=60)return{rating:'Proceed with Caution',recommendation:'The vendor meets some requirements, but several areas require clarification, stronger commitments or contractual protection.'};if(s>=40)return{rating:'High Risk',recommendation:'The vendor currently presents material delivery, quality or commercial risks. Request evidence, revise the engagement model or compare alternative vendors.'};return{rating:'Not Recommended',recommendation:'The vendor does not currently demonstrate sufficient readiness for a critical software project.'}}
export function getRedFlagSeverity(n:number){return n===0?'No Immediate Red Flags':n<=2?'Minor Concerns':n<=5?'Significant Concerns':'Critical Vendor Risk'}
export const PROJECT_TYPES=['SaaS platform','Custom business software','Mobile application','Web application','AI automation','CRM or ERP','E-commerce platform','System modernisation','API or third-party integration','Dedicated development team','Other'] as const;
export const ENGAGEMENT_MODELS=['Fixed-price project','Time and material','Dedicated development team','Staff augmentation','Retainer','Not decided'] as const;
